## Overview:

Los Angeles is a city/region known for its urban sprawl and car-oriented development. Despite this, Los Angeles is investing billions of dollars into its public transportation system to address the traffic congestion prevalent for its large population. An improved transportation system would bring the region to what is known as the Third Los Angeles: a new civic identity marked by more pedestrian-friendly and denser neighborhoods. This new era succeeds both the Second Los Angeles (the post-World War II era marked by the rise of the automobile, the freeway, and the single-family home) and the First Los Angeles (the pre-World War II era which laid the foundations for the city and included a vast network for public transportation destroyed, however, during the Second Los Angeles). However, the movement towards the Third Los Angeles faces resistance, predominantly from NIMBYs (an acronym for Not In My Back Yard, often used to refer to people who are anti-development). Major talking points for NIMBYs, upper-class NIMBYs in particular, about increased mass transit includes that it brings more unwanted people, particularly lower-income people, to their neighborhood, negatively impacts their homes' property values and shifts the character of their neighborhoods. However, public transportation could increase the values of surrounding land, therefore increasing the homes values surrounding it. 

As a result, this project analyzes the impact that a Los Angeles Metro station has on residential property values in Los Angeles County. 

Before the analytical portion of this project, data must be gathered through the following code:

## Data Cleaning for Zestimates Project

In [1]:
import pandas as pd
import numpy as np

#to ignore warnings
import warnings
warnings.filterwarnings('ignore')

#to reset how many max columns and rows I can see
pd.set_option('display.max_columns', None)

## Zestimate Data

Residential property values (the independent variable) for this project are measured through Zestimates. Zestimates (Zillow Estimates of housing values) are provided by Zillow through this link: https://www.zillow.com/research/data/

To access the Zestimate data used for this project, the following datasets were downloaded (on May 28th) from the Home Values section. The geography was selected as "ZIP Code".

- ZHVI All Homes (SFR, Condo/Co-op) Time Series, Smoothed, Seasonally Adjusted
- ZHVI Single-Family Homes Time Series
- ZHVI Condo/Co-op Homes Time Series
- ZHVI 1-Bedroom Time Series
- ZHVI 2-Bedroom Time Series
- ZHVI 3-Bedroom Time Series
- ZHVI 4-Bedroom Time Series
- ZHVI 5+ Bedroom Time Series

Once the data is downloaded, run the following (the code also limits for Zestimates from Jan 2000 to Apr 2022):

In [2]:
#for all Homes
all_homes_df = pd.read_csv('Data/Zip_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv') #use your own file's path

#limit the columns to Apr 2022 data
cols=list(all_homes_df.loc[:,'RegionID':'4/30/22'].columns)
all_homes_df = all_homes_df.loc[:,cols]

#for housetype
sfh_df = pd.read_csv('Data/Zip_zhvi_bdrmcnt_5_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv',usecols=cols) #use your own file's path

condo_df = pd.read_csv('Data/Zip_zhvi_uc_condo_tier_0.33_0.67_sm_sa_month.csv',usecols=cols) #use your own file's path

#for num of bedroom
bed1_df = pd.read_csv('Data/Zip_zhvi_bdrmcnt_1_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv',usecols=cols) #use your own file's path
bed2_df = pd.read_csv('Data/Zip_zhvi_bdrmcnt_2_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv',usecols=cols) #use your own file's path
bed3_df = pd.read_csv('Data/Zip_zhvi_bdrmcnt_3_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv',usecols=cols) #use your own file's path
bed4_df = pd.read_csv('Data/Zip_zhvi_bdrmcnt_4_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv',usecols=cols) #use your own file's path
bed5_df = pd.read_csv('Data/Zip_zhvi_bdrmcnt_5_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv',usecols=cols) #use your own file's path

all_homes_df #as example

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,1/31/00,2/29/00,3/31/00,4/30/00,5/31/00,6/30/00,7/31/00,8/31/00,9/30/00,10/31/00,11/30/00,12/31/00,1/31/01,2/28/01,3/31/01,4/30/01,5/31/01,6/30/01,7/31/01,8/31/01,9/30/01,10/31/01,11/30/01,12/31/01,1/31/02,2/28/02,3/31/02,4/30/02,5/31/02,6/30/02,7/31/02,8/31/02,9/30/02,10/31/02,11/30/02,12/31/02,1/31/03,2/28/03,3/31/03,4/30/03,5/31/03,6/30/03,7/31/03,8/31/03,9/30/03,10/31/03,11/30/03,12/31/03,1/31/04,2/29/04,3/31/04,4/30/04,5/31/04,6/30/04,7/31/04,8/31/04,9/30/04,10/31/04,11/30/04,12/31/04,1/31/05,2/28/05,3/31/05,4/30/05,5/31/05,6/30/05,7/31/05,8/31/05,9/30/05,10/31/05,11/30/05,12/31/05,1/31/06,2/28/06,3/31/06,4/30/06,5/31/06,6/30/06,7/31/06,8/31/06,9/30/06,10/31/06,11/30/06,12/31/06,1/31/07,2/28/07,3/31/07,4/30/07,5/31/07,6/30/07,7/31/07,8/31/07,9/30/07,10/31/07,11/30/07,12/31/07,1/31/08,2/29/08,3/31/08,4/30/08,5/31/08,6/30/08,7/31/08,8/31/08,9/30/08,10/31/08,11/30/08,12/31/08,1/31/09,2/28/09,3/31/09,4/30/09,5/31/09,6/30/09,7/31/09,8/31/09,9/30/09,10/31/09,11/30/09,12/31/09,1/31/10,2/28/10,3/31/10,4/30/10,5/31/10,6/30/10,7/31/10,8/31/10,9/30/10,10/31/10,11/30/10,12/31/10,1/31/11,2/28/11,3/31/11,4/30/11,5/31/11,6/30/11,7/31/11,8/31/11,9/30/11,10/31/11,11/30/11,12/31/11,1/31/12,2/29/12,3/31/12,4/30/12,5/31/12,6/30/12,7/31/12,8/31/12,9/30/12,10/31/12,11/30/12,12/31/12,1/31/13,2/28/13,3/31/13,4/30/13,5/31/13,6/30/13,7/31/13,8/31/13,9/30/13,10/31/13,11/30/13,12/31/13,1/31/14,2/28/14,3/31/14,4/30/14,5/31/14,6/30/14,7/31/14,8/31/14,9/30/14,10/31/14,11/30/14,12/31/14,1/31/15,2/28/15,3/31/15,4/30/15,5/31/15,6/30/15,7/31/15,8/31/15,9/30/15,10/31/15,11/30/15,12/31/15,1/31/16,2/29/16,3/31/16,4/30/16,5/31/16,6/30/16,7/31/16,8/31/16,9/30/16,10/31/16,11/30/16,12/31/16,1/31/17,2/28/17,3/31/17,4/30/17,5/31/17,6/30/17,7/31/17,8/31/17,9/30/17,10/31/17,11/30/17,12/31/17,1/31/18,2/28/18,3/31/18,4/30/18,5/31/18,6/30/18,7/31/18,8/31/18,9/30/18,10/31/18,11/30/18,12/31/18,1/31/19,2/28/19,3/31/19,4/30/19,5/31/19,6/30/19,7/31/19,8/31/19,9/30/19,10/31/19,11/30/19,12/31/19,1/31/20,2/29/20,3/31/20,4/30/20,5/31/20,6/30/20,7/31/20,8/31/20,9/30/20,10/31/20,11/30/20,12/31/20,1/31/21,2/28/21,3/31/21,4/30/21,5/31/21,6/30/21,7/31/21,8/31/21,9/30/21,10/31/21,11/30/21,12/31/21,1/31/22,2/28/22,3/31/22,4/30/22
0,70603,8175,29620,Zip,SC,SC,Abbeville,Greenwood,Abbeville County,62899.0,63130.0,63018.0,62809.0,62557.0,62393.0,62574.0,62764.0,63020.0,63115.0,63350.0,63677.0,64415.0,64927.0,65455.0,65448.0,65453.0,65500.0,65836.0,66150.0,66538.0,66897.0,67295.0,67476.0,68044.0,68515.0,69042.0,69124.0,69413.0,69542.0,69752.0,69852.0,70221.0,70527.0,70864.0,71052.0,71416.0,71729.0,72102.0,72316.0,72678.0,72889.0,73107.0,73282.0,73625.0,73792.0,73824.0,73887.0,74295.0,74622.0,74940.0,75068.0,75611.0,76087.0,76474.0,76815.0,77235.0,77782.0,78232.0,78678.0,79316.0,79893.0,80463.0,80808.0,81112.0,81556.0,82040.0,82574.0,83217.0,83942.0,84594.0,85119.0,85685.0,86219.0,86688.0,86999.0,87274.0,87690.0,88059.0,88768.0,89401.0,90245.0,90663.0,90965.0,91217.0,91574.0,91956.0,92183.0,92233.0,92249.0,92087.0,92293.0,92658.0,93215.0,93573.0,93925.0,94166.0,94378.0,94638.0,94757.0,95046.0,95079.0,95121.0,94869.0,94577.0,94415.0,94255.0,93769.0,92838.0,92140.0,91033.0,89888.0,88753.0,88252.0,88482.0,88244.0,87837.0,86996.0,86109.0,85143.0,84858.0,84920.0,85110.0,84830.0,84372.0,84692.0,84478.0,84389.0,84132.0,84191.0,84385.0,84377.0,83706.0,82679.0,81335.0,80669.0,80199.0,79953.0,79876.0,79669.0,79473.0,78971.0,78779.0,79915.0,81851.0,83783.0,84312.0,84475.0,84137.0,83874.0,83521.0,83592.0,83560.0,83770.0,84060.0,84450.0,84823.0,85398.0,86298.0,86883.0,87490.0,87528.0,87584.0,87570.0,87842.0,88029.0,88185.0,87981.0,87948.0,88059.0,88362.0,88815.0,89347.0,90529.0,91642.0,92094.0,92285.0,92596.0,93241.0,93451.0,93502.0,93603.0,93848.0,94449.0,95079.0,95634.0,96220.0,97193.0,98249.0,98879.0,99539.0,100066.0,100216.0,99925.0,100091.0,100637.0,101782.0,102426.0,102115.0,101465.0,101020.0,101293.0,101413.0,101535.0,101492.0,101274.0,101181.0,101725.0,102241.0,102728.0,103291.0,103979.0,104572.0,105185.0,105905.0,106814.0,107377.0,107750.0,110208.0,113036.0,115933.0,116468.0,117417.0,117957.0,118922.0,119030.0,119500.0,119615.0,120076.0,120666.0,121164.0,121816.0,122241.0,122793.0,123274.0,124246.0,125074.0,126125.0,126485.0,127034.0,126246.0,125932.0,125456.0,126043.0,126399.0,127135.0,127922.0,128600.0,129164.0,129836.0,130989.0,132234.0,134662.0,137041.0,139418.0,140793.0,141947.0,143243.0,144552.0,146180.0,147624.0,149035.0,150358.0,153712.0,156103.0,159531.0,160839.0,162905.0
1,70611,16664,29628,Zip,SC,SC,Calhoun Falls,Greenwood,Abbeville County,33021.0,33173.0,33329.0,33729.0,34073.0,34361.0,34552.0,34751.0,34886.0,34930.0,35047.0,35207.0,35223.0,35132.0,34667.0,34314.0,34046.0,34337.0,34637.0,34921.0,34886.0,34960.0,34980.0,35179.0,35013.0,34795.0,34896.0,35173.0,35494.0,35373.0,35573.0,35620.0,35936.0,36086.0,36463.0,36470.0,36236.0,35912.0,35902.0,36224.0,36641.0,36875.0,36950.0,36789.0,36650.0,36486.0,36713.0,36911.0,37015.0,36955.0,37132.0,37468.0,37685.0,37727.0,37867.0,38156.0,38367.0,38424.0,38507.0,38621.0,38639.0,38585.0,38364.0,37943.0,37541.0,37416.0,37618.0,37834.0,38374.0,38700.0,38885.0,38818.0,38942.0,39330.0,39705.0,39918.0,39981.0,39969.0,40184.0,40451.0,40790.0,41223.0,41425.0,41438.0,41274.0,41269.0,41228.0,41245.0,41196.0,41212.0,41118.0,41187.0,41207.0,41398.0,41387.0,41484.0,41496.0,41514.0,41736.0,41948.0,42150.0,42022.0,41960.0,41884.0,41794.0,41669.0,41545.0,41515.0,41153.0,40786.0,40397.0,40320.0,40173.0,39880.0,39531.0,39197.0,38890.0,38571.0,38082.0,37736.0,37253.0,36987.0,36686.0,36627.0,36595.0,36560.0,36486.0,36399.0,36236.0,36088.0,35776.0,35597.0,35387.0,35610.0,35761.0,35804.0,35625.0,35432.0,35423.0,35395.0,35343.0,35271.0,35237.0,35183.0,35037.0,34804.0,34677.0,34936.0,35186.0,35426.0,35392.0,35248.0,35081.0,35106.0,35364.0,35714.0,35887.0,35743.0,35568.0,35348.0,34867.0,34456.0,33881.0,33820.0,33218.0,31871.0,30622.0,29800.0,30059.0,30276.0,30521.0,30610.0,30745.0,30876.0,30732.0,30557.0,30661.0,30821.0,31034.0,31093.0,31130.0,31410.0,30762.0,30335.0,29612.0,29688.0,29824.0,29928.0,30051.0,30126.0,30261.0,30659.0,31179.0,31448.0,31527.0,31490.0,31727.0,31884.0,32101.0,32240.0,32507.0,32370.0,32297.0,32044.0,32177.0,32246.0,33023.0,33690.0,33785.0,33635.0,33306.0,33850.0,33887.0,34441.0,34683.0,35112.0,35276.0,35196.0,35516.0,35842.0,36623.0,36933.0,37446.0,37865.0,38649.0,39281.0,39756.0,39980.0,40493.0,41227.0,41728.0,41876.0,42158.0,42862.0,43621.0,44228.0,44473.0,44637.0,45160.0,45579.0,47224.0,48113.0,49398.0,49898.0,50901.0,51518.0,52382.0,52500.0,53287.0,53082.0,53053.0,52598.0,52999.0,53799.0,55548.0,57288.0,59442.0,60600.0,61094.0,61164.0,61096.0,61739.0,62299.0,64412.0,64227.0,64449.0,63424.0,64462.0
2,70619,16636,29638,Zip,SC,SC,Donalds,Greenwood,Abbeville County,61459.0,60772.0,60302.0,59142.0,58014.0,57162.0,56991.0,57151.0,57019.0,56904.0,57246.0,58091.0,58677.0,59263.0,60498.0,62164.0,63570.0,63709.0,64052.0,64323.0,65069.0,65742.0,66385.0,67073.0,67418.0,67630.0,67495.0,67599.0,68310.0,69399.0,70029.0,70204.0,70521.0,70985.0,71402.0,71304.0,71240.0,71151.0,71138.0,71469.0,72131.0,73096.0,73472.0,73987.0,74500.0,74837.0,74999.0,74843.0,74731.0,74324.0,74073.0,74220.0,74624.0,75321.0,75940.0,76439.0,76962.0,77461.0,78189.0,78627.0,78699.0,78331.0,77795.0,78026.0,78596.0,79684.0,80554.0,81192.0,81620.0,81936.0,82469.0,82937.0,83229.0,83459.0,83663.0,84226.0,84900.0,85815.0,86410.0,87240.0,88225.0,89361.0,90058.0,90206.0,90046.0,89873.0,89570.0,89669.0,89719.0,90207.0,90228.0,90641.0,90954.0,91434.0,91632.0,91789.0,92002.0,92206.0,92015.0,91971.0,91933.0,92226.0,92148.0,91923.0,91728.0,91566.0,91291.0,90791.0,90273.0,90489.0,90329.0,90404.0,89978.0,89651.0,89078.0,88137.0,87880.0,87565.0,87246.0,86691.0,86002.0,85574.0,84686.0,84094.0,83383.0,82981.0,82873.0,82847.0,83488.0,84000.0,84818.0,84838.0,84628.0,84028.0,83573.0,83464.0,83490.0,83425.0,83485.0,83253.0,83251.0,82722.0,82563.0,NaN,78487.0,76549.0,76636.0,76778.0,76788.0,76950.0,76682.0,76780.0,76612.0,76762.0,76874.0,77050.0,77261.0,77241.0,77495.0,77599.0,77754.0,77471.0,77211.0,76843.0,76761.0,76617.0,76558.0,76276.0,76597.0,76644.0,77547.0,77582.0,78115.0,78329.0,79323.0,80291.0,81193.0,81942.0,82379.0,82791.0,83180.0,83984.0,84595.0,85087.0,85529.0,86197.0,86779.0,87517.0,87895.0,88229.0,88417.0,88982.0,89458.0,89635.0,89794.0,89929.0,90596.0,91176.0,91486.0,91491.0,91268.0,91093.0,91040.0,91184.0,92014.0,92663.0,93305.0,93724.0,94321.0,94791.0,95294.0,95780.0,96091.0,96616.0,97144.0,98125.0,98037.0,97818.0,97958.0,98907.0,100066.0,100738.0,101510.0,102058.0,102684.0,102898.0,103097.0,103450.0,104017.0,104541.0,104345.0,104633.0,105015.0,106019.0,106970.0,107983.0,108249.0,108460.0,108242.0,108696.0,108692.0,109372.0,109737.0,110388.0,110392.0,110963.0,111586.0,112060.0,111880.0,111710.0,112269.0,112916.0,114653.0,116901.0,119334.0,121075.0,122616.0,124453.0,126341.0,127571.0,128568.0,129922.0,131800.0,135217.0,136599.0,138720.0,139121.0,141447.0
3,70620,22347,29639,Zip,SC,SC,Due West,Greenwood,Abbeville County,61564.0,61996.0,61322.0,59998.0,58233.0,57455.0,58068.0,58945.0,59284.0,58987.0,58825.0,59314.0,60325.0,61938.0,64029.0,65382.0,65748.0,64925.0,65212.0,65443.0,65857.0,66226.0,66738.0,67690.0,68996.0,70448.0,72057.0,72946.0,74403.0,75444.0,76208.0,76417.0,76891.0,77711.0,78814.0,79461.0,80210.0,80432.0,81731.0,82839.0,84475.0,85413.0,86152.0,86594.0,86925.0,87025.0,87397.0,87485.0,87994.0,87933.0,88408.0,88813.0,89632.0,90667.0,91331.0,91974.0,92268.0,92666.0,93445.0,94003.0,94837.0,95400.0,95952.0,96802.0,97318.0,98242.0,99063.0,100090.0,101382.0,102068.0,103115.0,103696.0,104478.0,104763.0,105273.0,105650.0,106081.0,107110.0,107928.0,109195.0,110208.0,111636.0,112326.0,112341.0,112317.0,112441.0,112515.0,112704.0,112642.0,112916.0,112844.0,113565.0,114392.0,115194.0,115733.0,115848.0,116197.0,116272.0,116429.0,116782.0,116996.0,117466.0,117211.0,117158.0,116970.0,116950.0,116466.0,115534.0,114531.0,113756.0,112529.0,111961.0,111579.0,111431.0,110785.0,110426.0,110601.0,110488.0,108816.0,107168.0,105200.0,104535.0,103182.0,102502.0,101510.0,101553.0,101343.0,101358.0,101109.0,101064.0,101282.0,101206.0,101189.0,100698.0,100159.0,99436.0,98861.0,99093.0,99369.0,99768.0,99550.0,99598.0,99628.0,98756.0,98020.0,97372.0,97665.0,98001.0,98096.0,98142.0,98133.0,98359.0,98588.0,98629.0,98514.0,98445.0,98861.0,99394.0,100218.0,100529.0,100915.0,100690.0,100481.0,100241.0,100297.0,100438.0,100861.0,101193.0,101613.0,101700.0,102327.0,102771.0,103247.0,103819.0,104250.0,104136.0,103674.0,103370.0,103830.0,104170.0,104201.0,103903.0,103855.0,104429.0,105210.0,105897.0,106353.0,107056.0,107979.0,108896.0,109402.0,109534.0,110208.0,111350.0,112622.0,113276.0,114123.0,114924.0,114363.0,113338.0,112241.0,112017.0,111902.0,112015.0,112665.0,113380.0,114131.0,114963.0,115378.0,115836.0,116464.0,117306.0,118083.0,118866.0,119822.0,120903.0,121251.0,121383.0,123875.0,127073.0,130502.0,131059.0,132324.0,132778.0,134346.0,134496.0,135039.0,135145.0,135825.0,136997.0,137479.0,138071.0,138520.0,139597.0,140766.0,142384.0,142929.0,143802.0,143846.0,144808.0,144391.0,144772.0,144378.0,145384.0,145824.0,147079.0,148029.0,148883.0,149266.0,149640.0,150596.0,151860.0,154457.0,157366.0,160676.0,162699.0,164537.0,166216.0,168810.0,171163.0,173006.0,174679.0,176077.0,180517.0,183075.0,187076.0,188075.0,189870.0
4,88648,8363,70525,Zip,LA,LA,Church Point,Lafayette,Acadia Parish,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134875.0,131268.0,127822.0,127658.0,126866.0,126127.0,125235.0,122459.0,117040.0,108605.0,100420.0,94694.0,91195.0,90165.0,89380.0,89561.0,89138.0,88645.0,88219.0,87815.0,87939.0,87638.0,87891.0,87567.0,86802.0,85928.0,86133.0,87144.0,88724.0,88827.0,89020.0,88235.0,88465.0,88436.0,88993.0,89109.0,89084.0,89564.0,91715.0,94162.0,95710.0,96514.0,97335.0,98185.0,98531.0,98504.0,98959.0,99229.0,99901.0,101160.0,103504.0,105150.0,105385.0,103301.0,102316.0,100920.0,101669.0,101829.0,104932.0,106243.0,107358.0,106397.0,106966.0,107235.0,107041.0,106736.0,107202.0,108495.0,109051.0,110503.0,112010.0,113678.0,112009.0,109578.0,106824.0,107015.0,107551.0,107393.0,106737.0,106847.0,108375.0,109527.0,110369.0,109162.0,108576.0,107766.0,109027.0,110028.0,110836.0,111028.0,111454.0,112218.0,113392.0,114549.0,115514.0,116627.0,117569.0,118361.0,118301.0,118164.0,118021.0,118366.0,118396.0,119744.0,121197.0,122595.0,122497.0,122690.0,122847.0,123531.0,122170.0,121107.0,120093.0,120550.0,121290.0,121384.0,121819.0,121889.0,122270.0,122085.0,122223.0,121607.0,120761.0,119461.0,118208.0,117698.0,116823.0,117037.0,117179.0,117747.0,118020.0,118686.0,120131.0,121103.0,120948.0,120355.0,120200.0,120830.0,121161.0,121607.0,122087.0,122598.0,123018.0,123494.0,124091.0,124634.0,124842.0,125083.0,125592.0,126341.0,126736.0,127242.0,127608.0,127977.0,128122.0,129649.0,131493.0,133420.0,134499.0,135696.0,136926.0,138032.0,138711.0,138708.0,138536.0,138822.0,139947.0,141341.0,142985.0,145717.0,148069.0,150009.0,150615.0,151486.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27334,92242,26414,78067,Zip,TX,TX,San Ygnacio,Zapata,Zapata County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40551.0,40875.0,41049.0,41390.0,41692.0,41612.0,41844.0,41844.0,42387.0,42343.0,42251.0,41439.0,40658.0,40199.0,40230.0,40467.0,40337.0,40260.0,40444.0,40740.0,41091.0,40953.0,41665.0,42330.0,43153.0,43676.0,43869.0,44423.0,44613.0,44758.0,44879.0,45100.0,45596.0,46186.0,46216.0,46216.0,45966.0,46355.0,47097.0,47377.0,47579.0,47243.0,47363.0,47303.0,47834.0,48171.0,48558.0,48969.0,49561.0,50222.0,50835.0,51331.0,51741.0,51784.0,52325.0,52638.0,53004.0,53038.0,53175.0,52967.0,52765.0,52644.0,53318.0,54132.0,55328.0,55802.0,56067.0,56730.0,57591.0,58342.0,58507.0,58629.0,58818.0,58827.0,59296.0,59510.0,60019.0,60059.0,60615.0,60601.0,61170.0,61498.0,61810.0,61750.0,61896.0,62274.0,63253.0,63997.0,64873.0,65097.0,65024.0,65068.0,65220.0,66144.0,66144.0,65859.0,65335.0,65627.0,66363.0,66346.0,65924.0,65771.0,65914.0,66522.0,67009.0,67506.0,67859.0,67917.0,68276.0,68187.0,68224.0,68196.0,68776.0,69120.0,69606.0,69269.0,69055.0,68745.0,68735.0,68119.0,67342.0,67046.0,66974.0,67313.0,67550.0,68281.0,68809.0,69637.0,70329.0,70945.0,70752.0,70172.0,69943.0,70388.0,71315.0,72599.0,73886.0,74645.0,74637.0,74505.0,74822.0,75271.0,75186.0,75618.0,76120.0,77370.0,79370.0,81313.0,83571.0,84337.0,85387.0
27335,92250,8183,78076,Zip,TX,TX,Zapata,Zapata,Zapata County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61475.0,61413.0,61442.0,61495.0,61731.0,62211.0,62732.0,62805.0,62613.0,62202.0,62200.0,61439.0,60994.0,60438.0,60507.0,60284.0,60253.0,60020.0,59899.0,59344.0,59174.0,58944.0,59664.0,60423.0,61524.0,61897.0,62325.0,62561.0,63197.0,63694.0,64286.0,64542.0,64652.0,64748.0,64778.0,64935.0,65178.0,65619.0,66183.0,66005.0,66014.0,65992.0,66653.0,66908.0,67334.0,67570.0,67721.0,67864.0,68138.0,68722.0,69278.0,69778.0,70440.0,71030.0,71748.0,72204.0,72648.0,73000.0,73410.0,73636.0,74067.0,74489.0,75278.0,76110.0,77246.0,78183.0,78984.0,79476.0,79906.0,80099.0,79956.0,79897.0,80079.0,80666.0,81276.0,81581.0,81977.0,82278.0,82843.0,83286.0,83767.0,84298.0,84822.0,85405.0,86293.0,87062.0,87813.0,88187.0,88626.0,89148.0,89777.0,90414.0,90765.0,91135.0,91036.0,90932.0,90622.0,90896.0,91438.0,92002.0,92590.0,93097.0,93246.0,93004.0,92916.0,93065.0,93415.0,93466.0,93651.0,93736.0,94419.0,95251.0,96390.0,97071.0,97800.0,98215.0,98688.0,98772.0,98858.0,98466.0,98007.0,97517.0,97351.0,97410.0,97438.0,97527.0,98409.0,99341.0,100403.0,100741.0,100625.0,100441.0,100467.0,101551.0,102460.0,104173.0,105636.0,107221.0,108112.0,109133.0,110283.0,111226.0,112070.0,112935.0,113510.0,113863.0,116163.0,118802.0,121548.0,122069.0,122238.0
27336,92696,24814,78829,Zip,TX,TX,Batesville,NaN,Zavala County,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52539.0,53214.0,52293.0,51708.0,50832.0,51281.0,51715.0,52172.0,52461.0,52520.0,52354.0,52035.0,51317.0,50631.0,51187.0,52379.0,53684.0,53830.0,53977.0,54132.0,54238.0,54812.0,55231.0,55989.0,56111.0,56362.0,57173.0,58226.0,59487.0,58937.0,56766.0,54873.0,54341.0,55454.0,55960.0,56322.0,56777.0,57714.0,58995.0,59876.0,60459.0,60706.0,61582.0,62256.0,62033.0,61152.0,60302.0,60445.0,60718.0,61331.0,61416.0,61823.0,62023.0,62570.0,62258.0,61844.0,61910.0,62749.0,63417.0,64453.0,64950.0,65399.0,63879.0,60762.0,58303.0,56454.0,56410.0,56476.0,57399.0,58914.0,60011.0,60503.0,60706.0,60897.0,63190.0,66029.0,66861.0,66693.0,65604.0,66365.0,66162.0,66619.0,67201.0,67928.0,67815.0,67485.0,67189.0,69097.0

In [3]:
df_list = [all_homes_df, sfh_df, condo_df, bed1_df, bed2_df, bed3_df, bed4_df, bed5_df]

#variables from each dataframe to drop (they all share the same ones)
variables_to_drop = ['index','RegionID','SizeRank','RegionType',
    'StateName','State','Metro','CountyName']

#list of dates (all dataframes cover the same months)
list_of_dates = all_homes_df.columns.to_list()[9:len(all_homes_df.columns)]


#the following creates inplace changes to the dataframes
for df in df_list:
    #drop all counties that aren't LA County
    df.drop(df[df['CountyName'] != 'Los Angeles County'].index,
           inplace=True)
        
    #sort values by RegionName aka ZIP Code
    df.sort_values('RegionName',inplace=True)
    
    #reset indeces
    df.reset_index(inplace=True, level=0)
    
    #drop all variables from the variables_to_drop list
    df.drop(columns=variables_to_drop,axis=1,inplace=True)

In [4]:
#turn the Zestimates into one column using melt()
all_homes_df = all_homes_df.melt(id_vars=['RegionName','City'], value_vars=list_of_dates, 
       var_name='Date',value_name='Zestimate')
sfh_df = sfh_df.melt(id_vars=['RegionName','City'], value_vars=list_of_dates,
       var_name='Date',value_name='Zestimate')
condo_df = condo_df.melt(id_vars=['RegionName','City'], value_vars=list_of_dates,
       var_name='Date',value_name='Zestimate')
bed1_df = bed1_df.melt(id_vars=['RegionName','City'], value_vars=list_of_dates,
       var_name='Date',value_name='Zestimate')
bed2_df = bed2_df.melt(id_vars=['RegionName','City'], value_vars=list_of_dates,
       var_name='Date',value_name='Zestimate')
bed3_df = bed3_df.melt(id_vars=['RegionName','City'], value_vars=list_of_dates,
       var_name='Date',value_name='Zestimate')
bed4_df = bed4_df.melt(id_vars=['RegionName','City'], value_vars=list_of_dates,
       var_name='Date',value_name='Zestimate')
bed5_df = bed5_df.melt(id_vars=['RegionName','City'], value_vars=list_of_dates,
       var_name='Date',value_name='Zestimate')

all_homes_df

       RegionName             City     Date  Zestimate
0           90001  Florence-Graham  1/31/00   146181.0
1           90002      Los Angeles  1/31/00   137086.0
2           90003      Los Angeles  1/31/00   138578.0
3           90004      Los Angeles  1/31/00   359034.0
4           90005      Los Angeles  1/31/00   251256.0
...           ...              ...      ...        ...
73427       93550         Palmdale  4/30/22   436526.0
73428       93551         Palmdale  4/30/22   599158.0
73429       93552         Palmdale  4/30/22   488423.0
73430       93553      Pearblossom  4/30/22   406237.0
73431       93591         Palmdale  4/30/22   360122.0

[73432 rows x 4 columns]

In [5]:
#reload list
df_list = [all_homes_df, sfh_df, condo_df, bed1_df, bed2_df, bed3_df, bed4_df, bed5_df]

for df in df_list:
    #rename 'RegionName' to 'ZIP'
    df.rename(columns={"RegionName":"ZIP"}, inplace=True)
    
    #drop na's
    df.dropna(inplace=True)
    
    #reset index
    df.reset_index(drop=True, inplace=True)
    
all_homes_df

         ZIP             City     Date  Zestimate
0      90001  Florence-Graham  1/31/00   146181.0
1      90002      Los Angeles  1/31/00   137086.0
2      90003      Los Angeles  1/31/00   138578.0
3      90004      Los Angeles  1/31/00   359034.0
4      90005      Los Angeles  1/31/00   251256.0
...      ...              ...      ...        ...
72916  93550         Palmdale  4/30/22   436526.0
72917  93551         Palmdale  4/30/22   599158.0
72918  93552         Palmdale  4/30/22   488423.0
72919  93553      Pearblossom  4/30/22   406237.0
72920  93591         Palmdale  4/30/22   360122.0

[72921 rows x 4 columns]

## Station Status Data

The primary dependent variable of interest for this project is station status. Station status is split into the following categories:

- 1) No LPA (Locally Preferred Alternative) 
- 2) Planning
- 3) Construction
- 4) Operational

In this research, the planning phase starts once Metro releases their Locally Preferred Alternative route (the route that becomes studied in the final Environmental Review report of the Metro line and eventually becomes the official route of a future line); the construction phase starts during the official groundbreaking ceremony for the construction of a line; and the operational phase starts once a station is opened.

Data was collected from the following sources:
- Metro's official website: https://www.metro.net/
- MTA Transportation Research Library & Archive: http://libraryarchives.metro.net/DPGTL/eirs/EIR_List.htm.
- Metro's The Source publication: https://thesource.metro.net/. 

ZIP codes with multiple transit lines have only one line represented: the line that best serves the entire ZIP Code.

The csv files used to collect the data are found in the GitHub page for this project: https://github.com/jeremiasfv22/Zestimates-and-Public-Transit-in-LA-County/tree/main/Data

In [6]:
#Import CSV files with line per zip, line type, and station status information
line_per_zip_df = pd.read_csv('Data/line per zip.csv') #use your own file's path
linetype_df = pd.read_csv('Data/line type.csv') #use your own file's path
station_status_df = pd.read_csv('Data/station status.csv') #use your own file's path

#reset indeces except for station_status_df
line_per_zip_df = line_per_zip_df.set_index('ZIP')
linetype_df = linetype_df.set_index('metro_line')

#melt the station station_status_df
metro_line_list = list(station_status_df.columns)
station_status_df = station_status_df.melt(id_vars='Date', value_vars=metro_line_list, var_name='MetroLine', value_name='StationStatus')

In [7]:
#individually merge all Metro data to each individual data frame, since there's no way to loop through df_list and do changes inplace
#remove metro_line and rename line_type
#if joins don't work, I recommend changing the date format from the Station Status csv file
all_homes_df = pd.merge(all_homes_df, line_per_zip_df, how='left', on=["ZIP"])
all_homes_df = pd.merge(all_homes_df, station_status_df, how='left', left_on=['Date','metro_line'], right_on = ['Date','MetroLine'])
all_homes_df = pd.merge(all_homes_df, linetype_df, how='left', on=['metro_line','metro_line'])
all_homes_df = all_homes_df.drop('metro_line', axis=1).rename(columns={'line_type':'LineType'})

sfh_df = pd.merge(sfh_df, line_per_zip_df, how='left', on=["ZIP"])
sfh_df = pd.merge(sfh_df, station_status_df, how='left', left_on=['Date','metro_line'], right_on = ['Date','MetroLine'])
sfh_df = pd.merge(sfh_df, linetype_df, how='left', on=['metro_line','metro_line'])
sfh_df = sfh_df.drop('metro_line', axis=1).rename(columns={'line_type':'LineType'})

condo_df = pd.merge(condo_df, line_per_zip_df, how='left', on=["ZIP"])
condo_df = pd.merge(condo_df, station_status_df, how='left', left_on=['Date','metro_line'], right_on = ['Date','MetroLine'])
condo_df = pd.merge(condo_df, linetype_df, how='left', on=['metro_line','metro_line'])
condo_df = condo_df.drop('metro_line', axis=1).rename(columns={'line_type':'LineType'})

bed1_df = pd.merge(bed1_df, line_per_zip_df, how='left', on=["ZIP"])
bed1_df = pd.merge(bed1_df, station_status_df, how='left', left_on=['Date','metro_line'], right_on = ['Date','MetroLine'])
bed1_df = pd.merge(bed1_df, linetype_df, how='left', on=['metro_line','metro_line'])
bed1_df = bed1_df.drop('metro_line', axis=1).rename(columns={'line_type':'LineType'})

bed2_df = pd.merge(bed2_df, line_per_zip_df, how='left', on=["ZIP"])
bed2_df = pd.merge(bed2_df, station_status_df, how='left', left_on=['Date','metro_line'], right_on = ['Date','MetroLine'])
bed2_df = pd.merge(bed2_df, linetype_df, how='left', on=['metro_line','metro_line'])
bed2_df = bed2_df.drop('metro_line', axis=1).rename(columns={'line_type':'LineType'})

bed3_df = pd.merge(bed3_df, line_per_zip_df, how='left', on=["ZIP"])
bed3_df = pd.merge(bed3_df, station_status_df, how='left', left_on=['Date','metro_line'], right_on = ['Date','MetroLine'])
bed3_df = pd.merge(bed3_df, linetype_df, how='left', on=['metro_line','metro_line'])
bed3_df = bed3_df.drop('metro_line', axis=1).rename(columns={'line_type':'LineType'})

bed4_df = pd.merge(bed4_df, line_per_zip_df, how='left', on=["ZIP"])
bed4_df = pd.merge(bed4_df, station_status_df, how='left', left_on=['Date','metro_line'], right_on = ['Date','MetroLine'])
bed4_df = pd.merge(bed4_df, linetype_df, how='left', on=['metro_line','metro_line'])
bed4_df = bed4_df.drop('metro_line', axis=1).rename(columns={'line_type':'LineType'})

bed5_df = pd.merge(bed5_df, line_per_zip_df, how='left', on=["ZIP"])
bed5_df = pd.merge(bed5_df, station_status_df, how='left', left_on=['Date','metro_line'], right_on = ['Date','MetroLine'])
bed5_df = pd.merge(bed5_df, linetype_df, how='left', on=['metro_line','metro_line'])
bed5_df = bed5_df.drop('metro_line', axis=1).rename(columns={'line_type':'LineType'})

bed3_df #as an example

,ZIP,City,Date,Zestimate,MetroLine,StationStatus,LineType
0,90001,Florence-Graham,1/31/00,140126.0,A Line,3.0,2.0
1,90002,Los Angeles,1/31/00,139954.0,A Line,3.0,2.0
2,90003,Los Angeles,1/31/00,134910.0,-,0.0,0.0
3,90004,Los Angeles,1/31/00,334572.0,B Line (to Hollywood/Vine),3.0,3.0
4,90005,Los Angeles,1/31/00,297468.0,D Line (to Wilshire/Western),3.0,3.0
...,...,...,...,...,...,...,...
71166,93550,Palmdale,4/30/22,425457.0,-,0.0,0.0
71167,93551,Palmdale,4/30/22,531849.0,-,0.0,0.0
71168,93552,Palmdale,4/30/22,451077.0,-,0.0,0.0
71169,93553,Pearblossom,4/30/22,428289.0,NaN,NaN,NaN
71170,93591,Palmdale,4/30/22,360317.0,-,0.0,0.0

## CalEnviroScreen 4.0 Data

Next, import data from CalEnviroScreen 4.0, the fourth version of the CalEnviroScreen done by California's Office of Environmental Health Hazard Assessment (OEHHA). CalEnviroScreen is a screening methodology that can be used to help identify California communities that are disproportionately burdened by multiple sources of pollution (California OEHHA, 2021). 

A link to the dataset (Excel file) used for CalEnviroScreen can be found here: https://oehha.ca.gov/calenviroscreen/report/calenviroscreen-40

Observations are by census tract (not ZIP Code). 

For this research, only the total population per census tract and the pullution burden score information (a control variable) are to be used. 

According to the California Office of Environmental Health Hazards Assessment, pollution burden scores (for each census tract) are derived from the average percentiles of seven exposure indicators (such as ozone, particular matter 2.5 concentration, diesel particular matter emissions, drinking water contaminants, children's lead risk from housing, pesticide use, toxic releases from facilities, and traffic density) and five environmental effects indicators (cleanup sites, impaired water bodies, groundwater threats, hazardous waste facilities and generators, and solid waste sites and facilities) (California OEHHA, 2021). 

The total population per census tract is taken from the United States Census Bureau (2021). 

The following code converts census-tract-level data to data on the zip code level using the ratio of population from census tract to ZIP Code.

In [8]:
calenviroscreen = pd.read_excel('Data/CalEnviroScreen_4.0Excel_ADA_D1_2021.xlsx') #use your own file's path

#replace all NaN values with None
calenviroscreen = calenviroscreen.replace(np.nan, "-")

#filter out for LA County
calenviroscreen = calenviroscreen[calenviroscreen['California County']=='Los Angeles']

#order by Census Tract ID
calenviroscreen = calenviroscreen.sort_values('Census Tract', ascending=True)

#reset index
calenviroscreen.index = range(len(calenviroscreen.index))

#select columns of interest
calenviroscreen = calenviroscreen.loc[:,['Census Tract',' Total Population','ZIP',
    'Nearby City \n(to help approximate location only)',
    'Pollution Burden Score']].rename(columns={" Total Population":"Total Population","Nearby City \n(to help approximate location only)":"Nearby City"})

In [9]:
#creates an TotalPopInZip col with "dashes as placeholders
calenviroscreen['TotalPopulation'] = "-"
calenviroscreen['PollutionBurdenScore'] = "-"

#creates a dictionary of total population per zip code
total_pop_in_zip = calenviroscreen.groupby(['ZIP'])['Total Population'].sum().to_dict()

for n in range(len(calenviroscreen)):
    #loops through total_pop col and changes it to equal what's in dct above
    calenviroscreen['TotalPopulation'][n] = total_pop_in_zip[calenviroscreen['ZIP'][n]]
    
    #loops through newly created Pullution Score per ZIP and gets weighted pollution scores per census tract (to be added up when dataframe is grouped by ZIP)
    calenviroscreen['PollutionBurdenScore'][n] = calenviroscreen['Pollution Burden Score'][n] * (calenviroscreen['Total Population'][n]/calenviroscreen['TotalPopulation'][n]) 

#group by ZIP Code and add weighted pollution scores, then convert to dataframe and set ZIP as index
pollution_and_totalpop = pd.DataFrame(calenviroscreen.groupby(['ZIP','TotalPopulation'])['PollutionBurdenScore'].sum()).reset_index()

#set ZIP as index
pollution_and_totalpop = pollution_and_totalpop.set_index('ZIP')
pollution_and_totalpop

       TotalPopulation PollutionBurdenScore
ZIP
90001            74964             7.101267
90002            59215             6.629903
90003            47765             7.197647
90004            58939              6.36398
90005            46348             5.874539
...                ...                  ...
93550            71378             3.387621
93551            55594             3.672139
93552            36091             3.033209
93563              795             4.659368
93591            12099             3.153774

[282 rows x 2 columns]

## Income
Income is another factor that can affect the median Zestimate values of an area. Income per ZIP Code for this project comes from the United States Census Bureau (2020 income in 2020 inflation-adjusted dollars). The csv file used for income can be found in the GitHub folder as well: https://github.com/jeremiasfv22/Zestimates-and-Public-Transit-in-LA-County/blob/main/Data/income.csv

In [10]:
income = pd.read_csv('Data/income.csv') #use your own file's path
income.set_index('ZIP')

        Income
ZIP
90001  48011.0
90002  42245.0
90003  42220.0
90004  52775.0
90005  42398.0
...        ...
93550  48002.0
93551  93637.0
93552  66289.0
93591  48911.0
90014  71358.0

[271 rows x 1 columns]

## Healthy Places Index 3.0 Data

Similar to above, import data from the California Healthy Places Index 3.0 (from the Public Health Alliance of Southern California). The Healthy Places Index (HPI) was created as a tool to explore the community conditions that impact life expentancy. Like CalEnviroScreen 4.0, The California HPI uses data from a variety of sources on a variety of community characteristics, like healthcare access, education access, exposure to pollutants, and more (HPI, 2022).

The data used for the HPI can be downloaded through here: https://map.healthyplacesindex.org/?redirect=false. From here, click on the Tools menubar, click Download Data, sign up for HPI account / sign in, get your API Key (from the dropdown on the upper right corner with your email/username), click "How do I use this" and select the indicator of choice. Alternatively, use this link (https://api.healthyplacesindex.org/documentation) 

Unlike the data used in CalEnviroScreen 4.0, HPI utilizes data at the ZIP Code level (as well as at the Census Tract level). 

For this research, the following variables are to be utilized (and their sources) as control variables:

* Homeownership - percentage of homeownership per ZIP Code (US Census Bureau, 2021)
* Commute - percentage of workers, ages 16 and older, commuting by walking, cycling, or transit (excluding work from home) per ZIP Code (US Census Bureau, 2021)
* Bachelor's Education - percentage of the population over age 25 with at least bachelor's degree per ZIP Code (US Census Bureau, 2021)
* Retail - combined employment density for retail, entertainment, supermarkets, and educational uses (measured in jobs per acre) per ZIP Code (US Census Bureau, 2020)
* Park Access - percentage of the population living within half a mile of a park, beach, or open space greater than 1 acre in size per ZIP Code (GreenInfo Network, 2017)
* Tree Canopy - population-weighted percentage of the ZIP Code with tree-canopy (National Land Cover Database, 2015)

In [11]:
homeownership = pd.read_csv('Data/homeownership.csv') #use your own file's path
commute = pd.read_csv('Data/commute.csv') #use your own file's path
bachelorsed = pd.read_csv('Data/bachelorsed.csv') #use your own file's path
retail = pd.read_csv('Data/retail.csv') #use your own file's path
parkaccess = pd.read_csv('Data/parkaccess.csv') #use your own file's path
treecanopy = pd.read_csv('Data/treecanopy.csv') #use your own file's path
walkability = pd.read_csv('Data/walkability.csv') #use your own file's path

walkability #as an example

      geoid   name      value  percentile  numerator  denominator
0     94601  94601  14.705952    0.891292        NaN          NaN
1     94501  94501  15.461917    0.945931        NaN          NaN
2     94560  94560  14.008831    0.821286        NaN          NaN
3     94587  94587  13.401415    0.746158        NaN          NaN
4     94580  94580  13.049099    0.710871        NaN          NaN
...     ...    ...        ...         ...        ...          ...
1763  95375  95375   6.279737    0.229368        NaN          NaN
1764  95627  95627   8.392513    0.385885        NaN          NaN
1765  95607  95607   9.109593    0.433125        NaN          NaN
1766  95919  95919   6.846151    0.273762        NaN          NaN
1767  95903  95903   7.019831    0.294821        NaN          NaN

[1768 rows x 6 columns]

In [12]:
hpi_dfs = [homeownership, commute, bachelorsed, 
           retail, parkaccess, treecanopy, walkability]

value_title_list = ['Homeownership','Commute','BachelorsEd',
                'Retail','ParkAccess','TreeCanopy','Walkability']


for df, title in zip(hpi_dfs, value_title_list):
    #drop all unnecessary columns
    df.drop(columns=['geoid','percentile',
                     'numerator','denominator'],
            axis=1,inplace=True)
    
    #drop all nan values
    df.dropna(inplace=True)
    
    #rename 'name' to ZIP
    df.rename(columns={'name':'ZIP'}, inplace=True)
    
    #rename 'value' to title in value_title_list
    df.rename(columns={'value':title}, inplace=True)
    
    #set index to 'ZIP'
    df.set_index('ZIP', inplace=True)

walkability.sort_values('ZIP') #example dct

       Walkability
ZIP
89010     6.351111
89019     6.021230
89060     6.708547
89061     6.708547
89439     5.108020
...            ...
96148    12.047014
96150    10.924529
96155     2.051279
96161     8.220060
97635     3.675800

[1768 rows x 1 columns]

Because there are ZIP Codes that don't belong to Los Angeles County here, these dictionaries will not be combined to a dataframe. They will instead be used to add values to existing dataframes.

## Crime Data

Crime data comes from CrimeGrade.org, an organization that collects ZIP Codes' and cities' crime data and assigns a score to it. 

The dataset can be found on Github here: https://github.com/jeremiasfv22/Zestimates-and-Public-Transit-in-LA-County/blob/main/Data/crimerates.csv 

For this project, only violent crime and property crime are to be used. 

Violent crime and property crime rates are measured per 1,000 people in each ZIP Code (CrimeGrade.org).

In [13]:
crime_rates_df = pd.read_csv('Data/crimerates.csv') 

#isolate for violent crime rates + property crime rates and set ZIP as index
crime_rates_df = crime_rates_df.loc[:,'ZIP':'property_crime_rates'].set_index('ZIP')
crime_rates_df.rename(columns={'violent_crime_rate':'ViolentCrimeRate','property_crime_rates':'PropertyCrimeRate',
                              'total_crime':'TotalCrime'},
                     inplace=True)
crime_rates_df

       TotalCrime  ViolentCrimeRate  PropertyCrimeRate
ZIP
90001     121.385            14.470              28.56
90002     107.673            14.760              26.29
90003     110.422            14.100              27.18
90004      97.800            10.690              39.78
90005     129.820            12.330              57.63
...           ...               ...                ...
93544      85.051             8.547              12.67
93550      42.691             4.482              15.95
93551      26.232             1.933              10.11
93552      44.118             2.048              12.72
93591      44.128             3.375              22.56

[270 rows x 3 columns]

## Mortgage Rate Data

Mortgage data is also to be collected. This data (monthly average commitment rate on 30-year fixed-rate mortgages since January 2000) is collected from Freddie Mac. 

The dataset can be found on GitHub here: https://github.com/jeremiasfv22/Zestimates-and-Public-Transit-in-LA-County/blob/main/Data/mortgage%20rates.csv

In [14]:
mortgages_df = pd.read_csv('/Users/jeremiasfigueroa/Data Projects/Zestimates and Train Stations in LA County/Data/mortgage rates.csv')
mortgages_df.rename(columns={'30-Year Fixed-Rate Mortgages Since 1971':'MortgageRate'}, inplace=True)
mortgages_df

         Date  MortgageRate
0     1/31/00          8.21
1     2/29/00          8.33
2     3/31/00          8.24
3     4/30/00          8.15
4     5/31/00          8.52
..        ...           ...
263  12/31/21          3.10
264   1/31/22          3.45
265   2/28/22          3.76
266   3/31/22          4.17
267   4/30/22          4.98

[268 rows x 2 columns]

# Latitude/Longitude Data

Lastly, Latitude and Longitude data is to be collected. For the possibility of expanding the project to a (computational intensive) geographically weighted regression analysis!!! 

Geocoordinate data is taken from the following: https://gist.github.com/erichurst/7882666

In [15]:
coordinates = pd.read_csv('Data/US-Zip-Codes-from-2013-Government-Data.csv')
coordinates.set_index('ZIP',inplace=True)
coordinates

             LAT         LNG
ZIP
601    18.180555  -66.749961
602    18.361945  -67.175597
603    18.455183  -67.119887
606    18.158345  -66.932911
610    18.295366  -67.125135
...          ...         ...
99923  56.002315 -130.041026
99925  55.550204 -132.945933
99926  55.138352 -131.470424
99927  56.239062 -133.457924
99929  56.370751 -131.693301

[33144 rows x 2 columns]

## Combining the data for each respective dataframe

In [16]:
all_homes_df = pd.merge(all_homes_df, coordinates, how='left', on=["ZIP","ZIP"])
all_homes_df = pd.merge(all_homes_df, pollution_and_totalpop, how='left', on=["ZIP","ZIP"])
all_homes_df = pd.merge(all_homes_df, income, how='left', on=["ZIP","ZIP"])
all_homes_df = pd.merge(all_homes_df, homeownership, how='left', on=["ZIP","ZIP"])
all_homes_df = pd.merge(all_homes_df, commute, how='left', on=["ZIP","ZIP"])
all_homes_df = pd.merge(all_homes_df, bachelorsed, how='left', on=["ZIP","ZIP"])
all_homes_df = pd.merge(all_homes_df, retail, how='left', on=["ZIP","ZIP"])
all_homes_df = pd.merge(all_homes_df, parkaccess, how='left', on=["ZIP","ZIP"])
all_homes_df = pd.merge(all_homes_df, treecanopy, how='left', on=["ZIP","ZIP"])
all_homes_df = pd.merge(all_homes_df, walkability, how='left', on=["ZIP","ZIP"])
all_homes_df = pd.merge(all_homes_df, crime_rates_df, how='left', on=["ZIP","ZIP"])
all_homes_df = pd.merge(all_homes_df, mortgages_df, how='left', on=["Date","Date"])

sfh_df = pd.merge(sfh_df, coordinates, how='left', on=["ZIP","ZIP"])
sfh_df = pd.merge(sfh_df, pollution_and_totalpop, how='left', on=["ZIP","ZIP"])
sfh_df = pd.merge(sfh_df, income, how='left', on=["ZIP","ZIP"])
sfh_df = pd.merge(sfh_df, homeownership, how='left', on=["ZIP","ZIP"])
sfh_df = pd.merge(sfh_df, commute, how='left', on=["ZIP","ZIP"])
sfh_df = pd.merge(sfh_df, bachelorsed, how='left', on=["ZIP","ZIP"])
sfh_df = pd.merge(sfh_df, retail, how='left', on=["ZIP","ZIP"])
sfh_df = pd.merge(sfh_df, parkaccess, how='left', on=["ZIP","ZIP"])
sfh_df = pd.merge(sfh_df, treecanopy, how='left', on=["ZIP","ZIP"])
sfh_df = pd.merge(sfh_df, walkability, how='left', on=["ZIP","ZIP"])
sfh_df = pd.merge(sfh_df, crime_rates_df, how='left', on=["ZIP","ZIP"])
sfh_df = pd.merge(sfh_df, mortgages_df, how='left', on=["Date","Date"])

condo_df = pd.merge(condo_df, coordinates, how='left', on=["ZIP","ZIP"])
condo_df = pd.merge(condo_df, pollution_and_totalpop, how='left', on=["ZIP","ZIP"])
condo_df = pd.merge(condo_df, income, how='left', on=["ZIP","ZIP"])
condo_df = pd.merge(condo_df, homeownership, how='left', on=["ZIP","ZIP"])
condo_df = pd.merge(condo_df, commute, how='left', on=["ZIP","ZIP"])
condo_df = pd.merge(condo_df, bachelorsed, how='left', on=["ZIP","ZIP"])
condo_df = pd.merge(condo_df, retail, how='left', on=["ZIP","ZIP"])
condo_df = pd.merge(condo_df, parkaccess, how='left', on=["ZIP","ZIP"])
condo_df = pd.merge(condo_df, treecanopy, how='left', on=["ZIP","ZIP"])
condo_df = pd.merge(condo_df, walkability, how='left', on=["ZIP","ZIP"])
condo_df = pd.merge(condo_df, crime_rates_df, how='left', on=["ZIP","ZIP"])
condo_df = pd.merge(condo_df, mortgages_df, how='left', on=["Date","Date"])

bed1_df = pd.merge(bed1_df, coordinates, how='left', on=["ZIP","ZIP"])
bed1_df = pd.merge(bed1_df, pollution_and_totalpop, how='left', on=["ZIP","ZIP"])
bed1_df = pd.merge(bed1_df, income, how='left', on=["ZIP","ZIP"])
bed1_df = pd.merge(bed1_df, homeownership, how='left', on=["ZIP","ZIP"])
bed1_df = pd.merge(bed1_df, commute, how='left', on=["ZIP","ZIP"])
bed1_df = pd.merge(bed1_df, bachelorsed, how='left', on=["ZIP","ZIP"])
bed1_df = pd.merge(bed1_df, retail, how='left', on=["ZIP","ZIP"])
bed1_df = pd.merge(bed1_df, parkaccess, how='left', on=["ZIP","ZIP"])
bed1_df = pd.merge(bed1_df, treecanopy, how='left', on=["ZIP","ZIP"])
bed1_df = pd.merge(bed1_df, walkability, how='left', on=["ZIP","ZIP"])
bed1_df = pd.merge(bed1_df, crime_rates_df, how='left', on=["ZIP","ZIP"])
bed1_df = pd.merge(bed1_df, mortgages_df, how='left', on=["Date","Date"])

bed2_df = pd.merge(bed2_df, coordinates, how='left', on=["ZIP","ZIP"])
bed2_df = pd.merge(bed2_df, pollution_and_totalpop, how='left', on=["ZIP","ZIP"])
bed2_df = pd.merge(bed2_df, income, how='left', on=["ZIP","ZIP"])
bed2_df = pd.merge(bed2_df, homeownership, how='left', on=["ZIP","ZIP"])
bed2_df = pd.merge(bed2_df, commute, how='left', on=["ZIP","ZIP"])
bed2_df = pd.merge(bed2_df, bachelorsed, how='left', on=["ZIP","ZIP"])
bed2_df = pd.merge(bed2_df, retail, how='left', on=["ZIP","ZIP"])
bed2_df = pd.merge(bed2_df, parkaccess, how='left', on=["ZIP","ZIP"])
bed2_df = pd.merge(bed2_df, treecanopy, how='left', on=["ZIP","ZIP"])
bed2_df = pd.merge(bed2_df, walkability, how='left', on=["ZIP","ZIP"])
bed2_df = pd.merge(bed2_df, crime_rates_df, how='left', on=["ZIP","ZIP"])
bed2_df = pd.merge(bed2_df, mortgages_df, how='left', on=["Date","Date"])

bed3_df = pd.merge(bed3_df, coordinates, how='left', on=["ZIP","ZIP"])
bed3_df = pd.merge(bed3_df, pollution_and_totalpop, how='left', on=["ZIP","ZIP"])
bed3_df = pd.merge(bed3_df, income, how='left', on=["ZIP","ZIP"])
bed3_df = pd.merge(bed3_df, homeownership, how='left', on=["ZIP","ZIP"])
bed3_df = pd.merge(bed3_df, commute, how='left', on=["ZIP","ZIP"])
bed3_df = pd.merge(bed3_df, bachelorsed, how='left', on=["ZIP","ZIP"])
bed3_df = pd.merge(bed3_df, retail, how='left', on=["ZIP","ZIP"])
bed3_df = pd.merge(bed3_df, parkaccess, how='left', on=["ZIP","ZIP"])
bed3_df = pd.merge(bed3_df, treecanopy, how='left', on=["ZIP","ZIP"])
bed3_df = pd.merge(bed3_df, walkability, how='left', on=["ZIP","ZIP"])
bed3_df = pd.merge(bed3_df, crime_rates_df, how='left', on=["ZIP","ZIP"])
bed3_df = pd.merge(bed3_df, mortgages_df, how='left', on=["Date","Date"])

bed4_df = pd.merge(bed4_df, coordinates, how='left', on=["ZIP","ZIP"])
bed4_df = pd.merge(bed4_df, pollution_and_totalpop, how='left', on=["ZIP","ZIP"])
bed4_df = pd.merge(bed4_df, income, how='left', on=["ZIP","ZIP"])
bed4_df = pd.merge(bed4_df, homeownership, how='left', on=["ZIP","ZIP"])
bed4_df = pd.merge(bed4_df, commute, how='left', on=["ZIP","ZIP"])
bed4_df = pd.merge(bed4_df, bachelorsed, how='left', on=["ZIP","ZIP"])
bed4_df = pd.merge(bed4_df, retail, how='left', on=["ZIP","ZIP"])
bed4_df = pd.merge(bed4_df, parkaccess, how='left', on=["ZIP","ZIP"])
bed4_df = pd.merge(bed4_df, treecanopy, how='left', on=["ZIP","ZIP"])
bed4_df = pd.merge(bed4_df, walkability, how='left', on=["ZIP","ZIP"])
bed4_df = pd.merge(bed4_df, crime_rates_df, how='left', on=["ZIP","ZIP"])
bed4_df = pd.merge(bed4_df, mortgages_df, how='left', on=["Date","Date"])

bed5_df = pd.merge(bed5_df, coordinates, how='left', on=["ZIP","ZIP"])
bed5_df = pd.merge(bed5_df, pollution_and_totalpop, how='left', on=["ZIP","ZIP"])
bed5_df = pd.merge(bed5_df, income, how='left', on=["ZIP","ZIP"])
bed5_df = pd.merge(bed5_df, homeownership, how='left', on=["ZIP","ZIP"])
bed5_df = pd.merge(bed5_df, commute, how='left', on=["ZIP","ZIP"])
bed5_df = pd.merge(bed5_df, bachelorsed, how='left', on=["ZIP","ZIP"])
bed5_df = pd.merge(bed5_df, retail, how='left', on=["ZIP","ZIP"])
bed5_df = pd.merge(bed5_df, parkaccess, how='left', on=["ZIP","ZIP"])
bed5_df = pd.merge(bed5_df, treecanopy, how='left', on=["ZIP","ZIP"])
bed5_df = pd.merge(bed5_df, walkability, how='left', on=["ZIP","ZIP"])
bed5_df = pd.merge(bed5_df, crime_rates_df, how='left', on=["ZIP","ZIP"])
bed5_df = pd.merge(bed5_df, mortgages_df, how='left', on=["Date","Date"])

sfh_df#as an example

,ZIP,City,Date,Zestimate,MetroLine,StationStatus,LineType,LAT,LNG,TotalPopulation,PollutionBurdenScore,Income,Homeownership,Commute,BachelorsEd,Retail,ParkAccess,TreeCanopy,Walkability,TotalCrime,ViolentCrimeRate,PropertyCrimeRate,MortgageRate
0,90001,Florence-Graham,1/31/00,190743.0,A Line,3.0,2.0,33.974027,-118.249509,74964,7.101267,48011.0,0.358768,0.155705,0.056269,7.536387,0.720039,0.036932,14.560535,121.385,14.470,28.56,8.21
1,90002,Los Angeles,1/31/00,172345.0,A Line,3.0,2.0,33.949099,-118.246737,59215,6.629903,42245.0,0.349694,0.154442,0.059574,3.175994,0.965845,0.046310,14.505535,107.673,14.760,26.29,8.21
2,90003,Los Angeles,1/31/00,176070.0,-,0.0,0.0,33.964131,-118.272783,47765,7.197647,42220.0,0.283002,0.149385,0.058099,3.890044,0.514657,0.039675,14.610410,110.422,14.100,27.18,8.21
3,90004,Los Angeles,1/31/00,481804.0,B Line (to Hollywood/Vine),3.0,3.0,34.076198,-118.310722,58939,6.36398,52775.0,0.165924,0.222401,0.350418,7.503799,0.580628,0.046591,15.078754,97.800,10.690,39.78,8.21
4,90005,Los Angeles,1/31/00,693093.0,D Line (to Wilshire/Western),3.0,3.0,34.059163,-118.306892,46348,5.874539,42398.0,0.077409,0.346879,0.313073,30.472961,0.762089,0.033707,16.131568,129.820,12.330,57.63,8.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62657,93536,Lancaster,4/30/22,624109.0,-,0.0,0.0,34.747390,-118.369249,71910,3.352665,84674.0,0.658702,0.021643,0.238092,1.593354,0.226433,0.026834,6.898064,65.691,3.915,18.53,4.98
62658,93543,Littlerock,4/30/22,547363.0,-,0.0,0.0,34.481108,-117.982006,14267,3.960144,57003.0,0.671714,0.003752,0.078076,0.186775,0.214444,0.010013,6.230231,37.946,3.127,13.52,4.98
62659,93550,Palmdale,4/30/22,539361.0,-,0.0,0.0,34.408548,-118.123592,71378,3.387621,48002.0,0.520744,0.038784,0.086532,1.361141,0.670852,0.032939,7.777514,42.691,4.482,15.95,4.98
62660,93551,Palmdale,4/30/22,674256.0,-,0.0,0.0,34.604105,-118.239213,55594,3.672139,93637.0,0.778644,0.016476,0.280265,1.339954,0.514021,0.033036,7.893055,26.232,1.933,10.11,4.98
62661,93552,Palmdale,4/30/22,583303.0,-,0.0,0.0,34.570867,-118.023744,36091,3.033209,66289.0,0.779829,0.029161,0.113580,0.840224,0.534562,0.014425,8.162668,44.118,2.048,12.72,4.98

In [17]:
#reload list
df_list = [all_homes_df, sfh_df, condo_df, bed1_df, bed2_df, bed3_df, bed4_df, bed5_df]

#list of columns to convert to int format
to_int = ['Zestimate','TotalPopulation','Income']

for df in df_list:
    
    #values with no MetroLine (and subsequentially no  StationStatus or LineType data)
    df.drop(df[df['MetroLine'].isna()].index, inplace=True)
    
    #values with no TotalPopulation (and subsequentially no PullutionBurdenScore)
    df.drop(df[df['TotalPopulation'].isna()].index, inplace=True)
    
    #select columns to change to floats/ints respectively
    df.loc[:,'PollutionBurdenScore':'MortgageRate'] = df.loc[:,'PollutionBurdenScore':'MortgageRate'].astype(float)
    df.loc[:,to_int] = df.loc[:,to_int].astype(int)
    df.loc[:,'StationStatus':'LineType'] = df.loc[:,'StationStatus':'LineType'].astype(int)
    

sfh_df #as an example

,ZIP,City,Date,Zestimate,MetroLine,StationStatus,LineType,LAT,LNG,TotalPopulation,PollutionBurdenScore,Income,Homeownership,Commute,BachelorsEd,Retail,ParkAccess,TreeCanopy,Walkability,TotalCrime,ViolentCrimeRate,PropertyCrimeRate,MortgageRate
0,90001,Florence-Graham,1/31/00,190743,A Line,3,2,33.974027,-118.249509,74964,7.101267,48011,0.358768,0.155705,0.056269,7.536387,0.720039,0.036932,14.560535,121.385,14.470,28.56,8.21
1,90002,Los Angeles,1/31/00,172345,A Line,3,2,33.949099,-118.246737,59215,6.629903,42245,0.349694,0.154442,0.059574,3.175994,0.965845,0.046310,14.505535,107.673,14.760,26.29,8.21
2,90003,Los Angeles,1/31/00,176070,-,0,0,33.964131,-118.272783,47765,7.197647,42220,0.283002,0.149385,0.058099,3.890044,0.514657,0.039675,14.610410,110.422,14.100,27.18,8.21
3,90004,Los Angeles,1/31/00,481804,B Line (to Hollywood/Vine),3,3,34.076198,-118.310722,58939,6.363980,52775,0.165924,0.222401,0.350418,7.503799,0.580628,0.046591,15.078754,97.800,10.690,39.78,8.21
4,90005,Los Angeles,1/31/00,693093,D Line (to Wilshire/Western),3,3,34.059163,-118.306892,46348,5.874539,42398,0.077409,0.346879,0.313073,30.472961,0.762089,0.033707,16.131568,129.820,12.330,57.63,8.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62657,93536,Lancaster,4/30/22,624109,-,0,0,34.747390,-118.369249,71910,3.352665,84674,0.658702,0.021643,0.238092,1.593354,0.226433,0.026834,6.898064,65.691,3.915,18.53,4.98
62658,93543,Littlerock,4/30/22,547363,-,0,0,34.481108,-117.982006,14267,3.960144,57003,0.671714,0.003752,0.078076,0.186775,0.214444,0.010013,6.230231,37.946,3.127,13.52,4.98
62659,93550,Palmdale,4/30/22,539361,-,0,0,34.408548,-118.123592,71378,3.387621,48002,0.520744,0.038784,0.086532,1.361141,0.670852,0.032939,7.777514,42.691,4.482,15.95,4.98
62660,93551,Palmdale,4/30/22,674256,-,0,0,34.604105,-118.239213,55594,3.672139,93637,0.778644,0.016476,0.280265,1.339954,0.514021,0.033036,7.893055,26.232,1.933,10.11,4.98
62661,93552,Palmdale,4/30/22,583303,-,0,0,34.570867,-118.023744,36091,3.033209,66289,0.779829,0.029161,0.113580,0.840224,0.534562,0.014425,8.162668,44.118,2.048,12.72,4.98

## Combining data for their respective models

Three datasets are to be used for the modeling portion of this project: one for Zestimates for all homes in a ZIP Code, regardless of housing type or the number of bedrooms a housing unit has, one for Zestimates based on the type of housing (condominiums/co-op units and single-family homes), different number of bedrooms (1-bedroom units, 2-bedroom units, 3-bedroom units, 4-bedroom units, and units with 5+ bedrooms). 

This split ensures the elimination of overlap amongst the data utilized in the models (i.e., a single-family home can be either a 2-bedroom unit or a 5+ bedroom unit or a 3-bedroom unit could be either a condominium/cooperative home or a single-family home, characteristics that the collected data does not take into account). 

For the dataset for housing type, 1 indicates a condominium and 0 indicates a single family home.

For the dataset for number of bedrooms, 1 indicates a 1-bedroom unit; 2 indicates a 2-bedroom unit; 3 indicates a 3-bedroom unit; 4 indicates a 4-bedroom unit; and 5 indicates a 5+ bedroom unit.

In [18]:
#Add new values on sfr_df and condo_df to indicate housing type 
sfh_df['HouseType'] = 1
condo_df['HouseType'] = 0

#merge the data together
housetype_df = pd.concat([sfh_df,condo_df], axis=0)
housetype_df.reset_index(drop=True, inplace=True)
housetype_df

,ZIP,City,Date,Zestimate,MetroLine,StationStatus,LineType,LAT,LNG,TotalPopulation,PollutionBurdenScore,Income,Homeownership,Commute,BachelorsEd,Retail,ParkAccess,TreeCanopy,Walkability,TotalCrime,ViolentCrimeRate,PropertyCrimeRate,MortgageRate,HouseType
0,90001,Florence-Graham,1/31/00,190743,A Line,3,2,33.974027,-118.249509,74964,7.101267,48011,0.358768,0.155705,0.056269,7.536387,0.720039,0.036932,14.560535,121.385,14.470,28.56,8.21,1
1,90002,Los Angeles,1/31/00,172345,A Line,3,2,33.949099,-118.246737,59215,6.629903,42245,0.349694,0.154442,0.059574,3.175994,0.965845,0.046310,14.505535,107.673,14.760,26.29,8.21,1
2,90003,Los Angeles,1/31/00,176070,-,0,0,33.964131,-118.272783,47765,7.197647,42220,0.283002,0.149385,0.058099,3.890044,0.514657,0.039675,14.610410,110.422,14.100,27.18,8.21,1
3,90004,Los Angeles,1/31/00,481804,B Line (to Hollywood/Vine),3,3,34.076198,-118.310722,58939,6.363980,52775,0.165924,0.222401,0.350418,7.503799,0.580628,0.046591,15.078754,97.800,10.690,39.78,8.21,1
4,90005,Los Angeles,1/31/00,693093,D Line (to Wilshire/Western),3,3,34.059163,-118.306892,46348,5.874539,42398,0.077409,0.346879,0.313073,30.472961,0.762089,0.033707,16.131568,129.820,12.330,57.63,8.21,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123961,93534,Lancaster,4/30/22,272564,-,0,0,34.713292,-118.152920,37427,4.326598,43247,0.343620,0.030925,0.164462,6.207458,0.503773,0.031308,10.155014,60.792,8.862,19.80,4.98,0
123962,93535,Lancaster,4/30/22,210439,-,0,0,34.713656,-117.864660,74358,3.815726,49304,0.566326,0.032056,0.111295,0.975277,0.278922,0.021886,7.008131,37.968,5.112,15.60,4.98,0
123963,93536,Lancaster,4/30/22,312069,-,0,0,34.747390,-118.369249,71910,3.352665,84674,0.658702,0.021643,0.238092,1.593354,0.226433,0.026834,6.898064,65.691,3.915,18.53,4.98,0
123964,93550,Palmdale,4/30/22,303761,-,0,0,34.408548,-118.123592,71378,3.387621,48002,0.520744,0.038784,0.086532,1.361141,0.670852,0.032939,7.777514,42.691,4.482,15.95,4.98,0
123965,93551,Palmdale,4/30/22,380828,-,0,0,34.604105,-118.239213,55594,3.672139,93637,0.778644,0.016476,0.280265,1.339954,0.514021,0.033036,7.893055,26.232,1.933,10.11,4.98,0

In [19]:
#Add new values on the following df's for num of bedrooms
bed1_df['BedroomNum'] = 1
bed2_df['BedroomNum'] = 2
bed3_df['BedroomNum'] = 3
bed4_df['BedroomNum'] = 4
bed5_df['BedroomNum'] = 5

#merge the data together
bedroom_df = pd.concat([bed1_df,bed2_df,bed3_df,bed4_df,bed5_df], axis=0)
bedroom_df.reset_index(drop=True, inplace=True)
bedroom_df

,ZIP,City,Date,Zestimate,MetroLine,StationStatus,LineType,LAT,LNG,TotalPopulation,PollutionBurdenScore,Income,Homeownership,Commute,BachelorsEd,Retail,ParkAccess,TreeCanopy,Walkability,TotalCrime,ViolentCrimeRate,PropertyCrimeRate,MortgageRate,BedroomNum
0,90001,Florence-Graham,1/31/00,85208,A Line,3,2,33.974027,-118.249509,74964,7.101267,48011,0.358768,0.155705,0.056269,7.536387,0.720039,0.036932,14.560535,121.385,14.470,28.56,8.21,1
1,90002,Los Angeles,1/31/00,104431,A Line,3,2,33.949099,-118.246737,59215,6.629903,42245,0.349694,0.154442,0.059574,3.175994,0.965845,0.046310,14.505535,107.673,14.760,26.29,8.21,1
2,90003,Los Angeles,1/31/00,110063,-,0,0,33.964131,-118.272783,47765,7.197647,42220,0.283002,0.149385,0.058099,3.890044,0.514657,0.039675,14.610410,110.422,14.100,27.18,8.21,1
3,90004,Los Angeles,1/31/00,157324,B Line (to Hollywood/Vine),3,3,34.076198,-118.310722,58939,6.363980,52775,0.165924,0.222401,0.350418,7.503799,0.580628,0.046591,15.078754,97.800,10.690,39.78,8.21,1
4,90011,Los Angeles,1/31/00,99017,A Line,3,2,34.007090,-118.258681,97020,6.620246,44616,0.259608,0.256329,0.052433,4.945700,0.789423,0.034513,15.420560,132.656,11.150,35.73,8.21,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312651,93536,Lancaster,4/30/22,624109,-,0,0,34.747390,-118.369249,71910,3.352665,84674,0.658702,0.021643,0.238092,1.593354,0.226433,0.026834,6.898064,65.691,3.915,18.53,4.98,5
312652,93543,Littlerock,4/30/22,547363,-,0,0,34.481108,-117.982006,14267,3.960144,57003,0.671714,0.003752,0.078076,0.186775,0.214444,0.010013,6.230231,37.946,3.127,13.52,4.98,5
312653,93550,Palmdale,4/30/22,539361,-,0,0,34.408548,-118.123592,71378,3.387621,48002,0.520744,0.038784,0.086532,1.361141,0.670852,0.032939,7.777514,42.691,4.482,15.95,4.98,5
312654,93551,Palmdale,4/30/22,674256,-,0,0,34.604105,-118.239213,55594,3.672139,93637,0.778644,0.016476,0.280265,1.339954,0.514021,0.033036,7.893055,26.232,1.933,10.11,4.98,5
312655,93552,Palmdale,4/30/22,583303,-,0,0,34.570867,-118.023744,36091,3.033209,66289,0.779829,0.029161,0.113580,0.840224,0.534562,0.014425,8.162668,44.118,2.048,12.72,4.98,5

# Now, save the dataframes!!

Copies of the final dataframes are also available on GitHub

In [20]:
all_homes_df.to_csv('Data/Zestimates for All Homes.csv', index=False)
housetype_df.to_csv('Data/Zestimates by House Type.csv', index=False)
bedroom_df.to_csv('Data/Zestimates by Bedroom Num.csv', index=False)

The data is now ready for analysis and modeling!!